import { Albun } from './albun';

export const DISCOGRAPHY: Albun[] = [
  {
    artist: 'Starset',
    id: 4,
    image: 'https://f4.bcbits.com/img/a3900848920_10.jpg',
    title: 'HORIZONS',
    recordLabel: 'Fearless Records',
    songs: [
      { number: 1, title: 'UNVEILING THE ARCHITECTURE', duration: '01:45' },
      { number: 2, title: 'THE BREACH', duration: '04:20' },
      { number: 3, title: 'OTHERWORLDLY', duration: '05:02' },
      { number: 4, title: 'ICARUS', duration: '04:48' },
      { number: 5, title: 'EARTHRISE', duration: '04:56' },
      { number: 6, title: 'LEAVING THIS WORLD BEHIND', duration: '04:27' },
      { number: 7, title: 'DEVOLUTION', duration: '05:09' },
      { number: 8, title: 'ANNIHILATED LOVE', duration: '04:44' },
      { number: 9, title: 'ALCHEMY', duration: '05:19' },
      { number: 10, title: 'DISAPPEAR', duration: '05:53' },
      { number: 11, title: 'THIS ENDLESS ENDEAVOR', duration: '05:02' },
      { number: 12, title: 'SYMBIOTIC', duration: '03:23' },
      { number: 13, title: 'DREAMCATCHER', duration: '04:53' },
      { number: 14, title: 'TUNNELVISION', duration: '04:09' },
      { number: 15, title: 'INFECTED', duration: '03:08' },
      { number: 16, title: 'SOMETHING WICKED', duration: '03:59' },
    ],
    released: 'October 22, 2021',
  },
  {
    artist: 'Starset',
    id: 3,
    image: 'https://f4.bcbits.com/img/a0405020972_10.jpg',
    title: 'DIVISIONS',
    recordLabel: 'Fearless Records',
    songs: [
      { number: 1, title: 'A BRIEF HISTORY OF THE FUTURE', duration: '01:37' },
      { number: 2, title: 'MANIFEST', duration: '04:27' },
      { number: 3, title: 'ECHO', duration: '03:36' },
      { number: 4, title: 'WHERE THE SKIES END', duration: '06:33' },
      { number: 5, title: 'PERFECT MACHINE', duration: '05:23' },
      { number: 6, title: 'TELEKINETIC', duration: '05:12' },
      { number: 7, title: 'STRATOSPHERE', duration: '04:17' },
      { number: 8, title: 'FAULTLINE', duration: '03:36' },
      { number: 9, title: 'SOLSTICE', duration: '05:41' },
      { number: 10, title: 'TRIALS', duration: '04:18' },
      { number: 11, title: 'WAKING UP', duration: '03:49' },
      { number: 12, title: 'OTHER WORLDS THAN THESE', duration: '04:18' },
      { number: 13, title: 'DIVING BELL', duration: '05:38' },
    ],
    released: 'September 13, 2019',
  },
  {
    id: 2,
    artist: 'Starset',
    image: 'https://f4.bcbits.com/img/a0544875558_10.jpg',
    title: 'Vessels',
    recordLabel: 'Razor & Tie',
    songs: [
      { number: 1, title: 'The Order', duration: '01:07' },
      { number: 2, title: 'Satellite', duration: '03:59' },
      { number: 3, title: 'Frequency', duration: '04:41' },
      { number: 4, title: 'DIE FOR YOU', duration: '05:17' },
      { number: 5, title: 'Ricochet', duration: '05:10' },
      { number: 6, title: 'Starlight', duration: '04:46' },
      { number: 7, title: 'Into The Unknown', duration: '04:30' },
      { number: 8, title: 'Gravity Of You', duration: '04:46' },
      { number: 9, title: 'Back To The Earth', duration: '04:13' },
      { number: 10, title: 'Last To Fall', duration: '05:03' },
      { number: 11, title: 'Bringing It Down', duration: '05:48' },
      { number: 12, title: 'Unbecoming', duration: '04:10' },
      { number: 13, title: 'Monster', duration: '04:16' },
      { number: 14, title: 'Telepathic', duration: '04:42' },
      { number: 15, title: 'Everglow', duration: '07:56' },
    ],
    released: 'January 20, 2017',
  },
];
